site_name: 'Documentació de les tasques'
docs_dir: 'docs_md'
site_dir: 'docs'
theme:
  name: 'material'
  custom_dir: 'overrides'
  palette:
    primary: 'indigo'
    accent: 'pink'
    background: 'white'
    surface: 'grey'
    error: 'red'

extra_css:
  - 'overrides/extra.css'
nav:
  - Inici: index.md
  - EDD:
    - Article sobre com plantejarieu el desenvolupament d'una app (llenguatges, tecnologies, etc.): EDD/ARTICULOS/ARTICLE_2.md
    - Buscar els llenguatges més utilitzats i indicar les seues característiques (a mode de ressum d'aquest article podríes incloure alguna taula amb Markdown): EDD/ARTICULOS/ARTICLE_1.md
    - Exemples de traducció. Les ordres python3, cc, java i javac.: EDD/ARTICULOS/ARTICLE_3.md
    - L'efecte Bola de neu.: EDD/ARTICULOS/ARTICLE_4.md
    - La web d'una empresa: EDD/ARTICULOS/ARTICLE_5.md
    - Scrum, Comflicte d'interessos: EDD/ARTICULOS/ARTICLE_6.md
  - LMI:
    - Identifcar caracteristiques dels llenguatges de marques en diferents documents: LMI/ARTICULOS/ARTICLE_1.md
    - Identificació dels espais de noms en documents (AndroidManifest.xml).: LMI/ARTICULOS/ARTICLE_2.md